# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90aec5a844f4fe8ebe0f2c76b4973cc81b58ae384aadfcd890a1e38e19be01ce813b8e25d6581adbc86971219b996c64263040450725930b0939e76ce4399a80

test:
  secret_key_base: 2165570cab94c96d6d8c828b27b0c3c3bd419e081be6ae720eece74ffb8b066e8f9a672efdaf3275d825f02b96e3dd5c667db901d729183567241f0f26bc4867

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
